-- AlterTable
ALTER TABLE "Server" ALTER COLUMN "networkIn" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "networkOut" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ServerMetric" ALTER COLUMN "networkIn" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "networkOut" SET DATA TYPE DOUBLE PRECISION;
