-- AlterTable
ALTER TABLE "Node" ADD COLUMN     "statsPort" INTEGER,
ADD COLUMN     "trafficDownBytes" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "trafficUpBytes" DOUBLE PRECISION NOT NULL DEFAULT 0;
